pal0_params:
	dd 5.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal1_params:
	dd 7.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal2_params:
	dd 0.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal3_params:
	dd 12.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal4_params:
	dd 12.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal5_params:
	dd 8.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal6_params:
	dd 17.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal7_params:
	dd 13.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal8_params:
	dd 2.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal9_params:
	dd 5.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal10_params:
	dd 9.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal11_params:
	dd 3.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal12_params:
	dd 11.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal13_params:
	dd 7.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal14_params:
	dd 6.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal15_params:
	dd 8.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal16_params:
	dd 8.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal17_params:
	dd 16.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal18_params:
	dd 5.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal19_params:
	dd 17.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal20_params:
	dd 4.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal21_params:
	dd 4.0
	dd 65.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal22_params:
	dd 14.0
	dd 3.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal23_params:
	dd 19.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal24_params:
	dd 11.0
	dd 59.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal25_params:
	dd 10.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal26_params:
	dd 19.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal27_params:
	dd 0.0
	dd 65.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal28_params:
	dd 5.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal29_params:
	dd 7.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal30_params:
	dd 1.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal31_params:
	dd 6.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal32_params:
	dd 17.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal33_params:
	dd 12.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal34_params:
	dd 12.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal35_params:
	dd 17.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal36_params:
	dd 3.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal37_params:
	dd 13.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal38_params:
	dd 0.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal39_params:
	dd 13.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal40_params:
	dd 18.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal41_params:
	dd 4.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal42_params:
	dd 16.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal43_params:
	dd 2.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal44_params:
	dd 17.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal45_params:
	dd 14.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal46_params:
	dd 8.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal47_params:
	dd 14.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal48_params:
	dd 4.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal49_params:
	dd 12.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal50_params:
	dd 19.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal51_params:
	dd 18.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal52_params:
	dd 5.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal53_params:
	dd 12.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal54_params:
	dd 18.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal55_params:
	dd 10.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal56_params:
	dd 14.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal57_params:
	dd 12.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal58_params:
	dd 6.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal59_params:
	dd 17.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal60_params:
	dd 8.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal61_params:
	dd 6.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal62_params:
	dd 12.0
	dd 2.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal63_params:
	dd 17.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal64_params:
	dd 0.0
	dd 6.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal65_params:
	dd 13.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal66_params:
	dd 6.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal67_params:
	dd 13.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal68_params:
	dd 8.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal69_params:
	dd 15.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal70_params:
	dd 8.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal71_params:
	dd 11.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal72_params:
	dd 12.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal73_params:
	dd 5.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal74_params:
	dd 10.0
	dd 4.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal75_params:
	dd 19.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal76_params:
	dd 0.0
	dd 59.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal77_params:
	dd 0.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal78_params:
	dd 14.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal79_params:
	dd 12.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal80_params:
	dd 16.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal81_params:
	dd 16.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal82_params:
	dd 4.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal83_params:
	dd 13.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal84_params:
	dd 17.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal85_params:
	dd 9.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal86_params:
	dd 4.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal87_params:
	dd 5.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal88_params:
	dd 17.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal89_params:
	dd 10.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal90_params:
	dd 19.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal91_params:
	dd 2.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal92_params:
	dd 6.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal93_params:
	dd 17.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal94_params:
	dd 8.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal95_params:
	dd 9.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal96_params:
	dd 16.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal97_params:
	dd 6.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal98_params:
	dd 8.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal99_params:
	dd 9.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal100_params:
	dd 18.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal101_params:
	dd 14.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal102_params:
	dd 19.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal103_params:
	dd 5.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal104_params:
	dd 10.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal105_params:
	dd 9.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal106_params:
	dd 12.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal107_params:
	dd 10.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal108_params:
	dd 11.0
	dd 60.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal109_params:
	dd 11.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal110_params:
	dd 18.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal111_params:
	dd 13.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal112_params:
	dd 15.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal113_params:
	dd 9.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal114_params:
	dd 6.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal115_params:
	dd 11.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal116_params:
	dd 19.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal117_params:
	dd 6.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal118_params:
	dd 11.0
	dd 62.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal119_params:
	dd 13.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal120_params:
	dd 9.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal121_params:
	dd 0.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal122_params:
	dd 11.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal123_params:
	dd 1.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal124_params:
	dd 3.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal125_params:
	dd 14.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal126_params:
	dd 11.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal127_params:
	dd 8.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal128_params:
	dd 16.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal129_params:
	dd 2.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal130_params:
	dd 1.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal131_params:
	dd 17.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal132_params:
	dd 11.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal133_params:
	dd 6.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal134_params:
	dd 7.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal135_params:
	dd 1.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal136_params:
	dd 1.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal137_params:
	dd 7.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal138_params:
	dd 18.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal139_params:
	dd 3.0
	dd 6.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal140_params:
	dd 10.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal141_params:
	dd 0.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal142_params:
	dd 10.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal143_params:
	dd 9.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal144_params:
	dd 14.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal145_params:
	dd 11.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal146_params:
	dd 3.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal147_params:
	dd 15.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal148_params:
	dd 5.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal149_params:
	dd 11.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal150_params:
	dd 15.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal151_params:
	dd 11.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal152_params:
	dd 19.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal153_params:
	dd 0.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal154_params:
	dd 17.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal155_params:
	dd 0.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal156_params:
	dd 15.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal157_params:
	dd 3.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal158_params:
	dd 14.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal159_params:
	dd 5.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal160_params:
	dd 13.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal161_params:
	dd 16.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal162_params:
	dd 13.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal163_params:
	dd 19.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal164_params:
	dd 9.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal165_params:
	dd 8.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal166_params:
	dd 11.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal167_params:
	dd 13.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal168_params:
	dd 13.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal169_params:
	dd 16.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal170_params:
	dd 2.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal171_params:
	dd 2.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal172_params:
	dd 1.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal173_params:
	dd 15.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal174_params:
	dd 11.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal175_params:
	dd 13.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal176_params:
	dd 12.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal177_params:
	dd 3.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal178_params:
	dd 9.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal179_params:
	dd 15.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal180_params:
	dd 17.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal181_params:
	dd 16.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal182_params:
	dd 4.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal183_params:
	dd 14.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal184_params:
	dd 18.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal185_params:
	dd 9.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal186_params:
	dd 7.0
	dd 2.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal187_params:
	dd 13.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal188_params:
	dd 19.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal189_params:
	dd 5.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal190_params:
	dd 12.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal191_params:
	dd 5.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal192_params:
	dd 6.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal193_params:
	dd 12.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal194_params:
	dd 4.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal195_params:
	dd 6.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal196_params:
	dd 1.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal197_params:
	dd 10.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal198_params:
	dd 0.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal199_params:
	dd 6.0
	dd 64.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal0_params:
	dd 2.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal1_params:
	dd 19.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal2_params:
	dd 12.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal3_params:
	dd 5.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal4_params:
	dd 11.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal5_params:
	dd 11.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal6_params:
	dd 17.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal7_params:
	dd 7.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal8_params:
	dd 2.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal9_params:
	dd 7.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal10_params:
	dd 2.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal11_params:
	dd 5.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal12_params:
	dd 16.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal13_params:
	dd 1.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal14_params:
	dd 2.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal15_params:
	dd 11.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal16_params:
	dd 15.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal17_params:
	dd 1.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal18_params:
	dd 14.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal19_params:
	dd 3.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal20_params:
	dd 1.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal21_params:
	dd 14.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal22_params:
	dd 11.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal23_params:
	dd 13.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal24_params:
	dd 15.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal25_params:
	dd 4.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal26_params:
	dd 4.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal27_params:
	dd 14.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal28_params:
	dd 18.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal29_params:
	dd 9.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal30_params:
	dd 3.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal31_params:
	dd 8.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal32_params:
	dd 12.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal33_params:
	dd 11.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal34_params:
	dd 3.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal35_params:
	dd 3.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal36_params:
	dd 8.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal37_params:
	dd 9.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal38_params:
	dd 5.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal39_params:
	dd 11.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal40_params:
	dd 3.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal41_params:
	dd 3.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal42_params:
	dd 14.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal43_params:
	dd 5.0
	dd 5.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal44_params:
	dd 5.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal45_params:
	dd 18.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal46_params:
	dd 7.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal47_params:
	dd 19.0
	dd 59.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal48_params:
	dd 2.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal49_params:
	dd 16.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal50_params:
	dd 14.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal51_params:
	dd 3.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal52_params:
	dd 1.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal53_params:
	dd 0.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal54_params:
	dd 11.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal55_params:
	dd 16.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal56_params:
	dd 16.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal57_params:
	dd 9.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal58_params:
	dd 16.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal59_params:
	dd 1.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal60_params:
	dd 9.0
	dd 6.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal61_params:
	dd 3.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal62_params:
	dd 17.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal63_params:
	dd 0.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal64_params:
	dd 2.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal65_params:
	dd 16.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal66_params:
	dd 18.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal67_params:
	dd 18.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal68_params:
	dd 2.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal69_params:
	dd 18.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal70_params:
	dd 13.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal71_params:
	dd 5.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal72_params:
	dd 15.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal73_params:
	dd 16.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal74_params:
	dd 0.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal75_params:
	dd 13.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal76_params:
	dd 17.0
	dd 62.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal77_params:
	dd 13.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal78_params:
	dd 11.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal79_params:
	dd 14.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal80_params:
	dd 19.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal81_params:
	dd 3.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal82_params:
	dd 14.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal83_params:
	dd 12.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal84_params:
	dd 19.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal85_params:
	dd 0.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal86_params:
	dd 12.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal87_params:
	dd 19.0
	dd 1.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal88_params:
	dd 14.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal89_params:
	dd 17.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal90_params:
	dd 3.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal91_params:
	dd 8.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal92_params:
	dd 8.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal93_params:
	dd 10.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal94_params:
	dd 12.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal95_params:
	dd 6.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal96_params:
	dd 12.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal97_params:
	dd 11.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal98_params:
	dd 18.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal99_params:
	dd 8.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal100_params:
	dd 3.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal101_params:
	dd 6.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal102_params:
	dd 5.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal103_params:
	dd 14.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal104_params:
	dd 16.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal105_params:
	dd 4.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal106_params:
	dd 3.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal107_params:
	dd 10.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal108_params:
	dd 10.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal109_params:
	dd 17.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal110_params:
	dd 9.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal111_params:
	dd 16.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal112_params:
	dd 8.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal113_params:
	dd 16.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal114_params:
	dd 13.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal115_params:
	dd 12.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal116_params:
	dd 0.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal117_params:
	dd 18.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal118_params:
	dd 15.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal119_params:
	dd 6.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal120_params:
	dd 2.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal121_params:
	dd 16.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal122_params:
	dd 12.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal123_params:
	dd 4.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal124_params:
	dd 9.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal125_params:
	dd 9.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal126_params:
	dd 1.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal127_params:
	dd 2.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal128_params:
	dd 3.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal129_params:
	dd 8.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal130_params:
	dd 18.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal131_params:
	dd 5.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal132_params:
	dd 7.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal133_params:
	dd 18.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal134_params:
	dd 13.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal135_params:
	dd 1.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal136_params:
	dd 6.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal137_params:
	dd 18.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal138_params:
	dd 9.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal139_params:
	dd 5.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal140_params:
	dd 18.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal141_params:
	dd 7.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal142_params:
	dd 14.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal143_params:
	dd 6.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal144_params:
	dd 4.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal145_params:
	dd 9.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal146_params:
	dd 9.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal147_params:
	dd 18.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal148_params:
	dd 19.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal149_params:
	dd 1.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal150_params:
	dd 14.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal151_params:
	dd 3.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal152_params:
	dd 3.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal153_params:
	dd 2.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal154_params:
	dd 4.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal155_params:
	dd 9.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal156_params:
	dd 7.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal157_params:
	dd 13.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal158_params:
	dd 12.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal159_params:
	dd 16.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal160_params:
	dd 17.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal161_params:
	dd 2.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal162_params:
	dd 0.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal163_params:
	dd 10.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal164_params:
	dd 10.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal165_params:
	dd 15.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal166_params:
	dd 9.0
	dd 61.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal167_params:
	dd 0.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal168_params:
	dd 17.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal169_params:
	dd 3.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal170_params:
	dd 18.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal171_params:
	dd 1.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal172_params:
	dd 15.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal173_params:
	dd 18.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal174_params:
	dd 6.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal175_params:
	dd 10.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal176_params:
	dd 11.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal177_params:
	dd 7.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal178_params:
	dd 8.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal179_params:
	dd 19.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal180_params:
	dd 1.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal181_params:
	dd 0.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal182_params:
	dd 18.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal183_params:
	dd 17.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal184_params:
	dd 10.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal185_params:
	dd 12.0
	dd 63.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal186_params:
	dd 6.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal187_params:
	dd 19.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal188_params:
	dd 14.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal189_params:
	dd 13.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal190_params:
	dd 19.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal191_params:
	dd 5.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal192_params:
	dd 13.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal193_params:
	dd 11.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal194_params:
	dd 18.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal195_params:
	dd 6.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal196_params:
	dd 18.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal197_params:
	dd 9.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal198_params:
	dd 17.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal199_params:
	dd 4.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal0_params:
	dd 7.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal1_params:
	dd 3.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal2_params:
	dd 14.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal3_params:
	dd 16.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal4_params:
	dd 9.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal5_params:
	dd 1.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal6_params:
	dd 8.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal7_params:
	dd 0.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal8_params:
	dd 4.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal9_params:
	dd 2.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal10_params:
	dd 19.0
	dd 60.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal11_params:
	dd 10.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal12_params:
	dd 19.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal13_params:
	dd 15.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal14_params:
	dd 16.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal15_params:
	dd 15.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal16_params:
	dd 5.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal17_params:
	dd 12.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal18_params:
	dd 14.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal19_params:
	dd 7.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal20_params:
	dd 17.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal21_params:
	dd 9.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal22_params:
	dd 14.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal23_params:
	dd 6.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal24_params:
	dd 18.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal25_params:
	dd 19.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal26_params:
	dd 17.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal27_params:
	dd 13.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal28_params:
	dd 19.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal29_params:
	dd 11.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal30_params:
	dd 12.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal31_params:
	dd 14.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal32_params:
	dd 10.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal33_params:
	dd 12.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal34_params:
	dd 4.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal35_params:
	dd 5.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal36_params:
	dd 13.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal37_params:
	dd 2.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal38_params:
	dd 18.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal39_params:
	dd 13.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal40_params:
	dd 7.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal41_params:
	dd 9.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal42_params:
	dd 11.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal43_params:
	dd 18.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal44_params:
	dd 19.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal45_params:
	dd 19.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal46_params:
	dd 15.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal47_params:
	dd 7.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal48_params:
	dd 13.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal49_params:
	dd 1.0
	dd 64.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal50_params:
	dd 11.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal51_params:
	dd 17.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal52_params:
	dd 5.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal53_params:
	dd 10.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal54_params:
	dd 11.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal55_params:
	dd 11.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal56_params:
	dd 15.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal57_params:
	dd 7.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal58_params:
	dd 7.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal59_params:
	dd 12.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal60_params:
	dd 13.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal61_params:
	dd 16.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal62_params:
	dd 4.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal63_params:
	dd 7.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal64_params:
	dd 2.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal65_params:
	dd 6.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal66_params:
	dd 6.0
	dd 59.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal67_params:
	dd 1.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal68_params:
	dd 18.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal69_params:
	dd 1.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal70_params:
	dd 7.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal71_params:
	dd 10.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal72_params:
	dd 7.0
	dd 64.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal73_params:
	dd 8.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal74_params:
	dd 10.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal75_params:
	dd 19.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal76_params:
	dd 14.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal77_params:
	dd 7.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal78_params:
	dd 3.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal79_params:
	dd 8.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal80_params:
	dd 4.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal81_params:
	dd 19.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal82_params:
	dd 0.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal83_params:
	dd 8.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal84_params:
	dd 14.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal85_params:
	dd 6.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal86_params:
	dd 3.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal87_params:
	dd 18.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal88_params:
	dd 16.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal89_params:
	dd 15.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal90_params:
	dd 5.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal91_params:
	dd 9.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal92_params:
	dd 4.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal93_params:
	dd 14.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal94_params:
	dd 15.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal95_params:
	dd 3.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal96_params:
	dd 14.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal97_params:
	dd 16.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal98_params:
	dd 13.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal99_params:
	dd 5.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal100_params:
	dd 2.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal101_params:
	dd 1.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal102_params:
	dd 6.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal103_params:
	dd 5.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal104_params:
	dd 13.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal105_params:
	dd 9.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal106_params:
	dd 9.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal107_params:
	dd 14.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal108_params:
	dd 19.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal109_params:
	dd 2.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal110_params:
	dd 19.0
	dd 63.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal111_params:
	dd 18.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal112_params:
	dd 19.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal113_params:
	dd 1.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal114_params:
	dd 1.0
	dd 59.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal115_params:
	dd 0.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal116_params:
	dd 15.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal117_params:
	dd 7.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal118_params:
	dd 11.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal119_params:
	dd 0.0
	dd 64.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal120_params:
	dd 1.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal121_params:
	dd 2.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal122_params:
	dd 4.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal123_params:
	dd 3.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal124_params:
	dd 1.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal125_params:
	dd 0.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal126_params:
	dd 19.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal127_params:
	dd 13.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal128_params:
	dd 7.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal129_params:
	dd 2.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal130_params:
	dd 17.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal131_params:
	dd 0.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal132_params:
	dd 2.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal133_params:
	dd 11.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal134_params:
	dd 4.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal135_params:
	dd 16.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal136_params:
	dd 14.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal137_params:
	dd 1.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal138_params:
	dd 19.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal139_params:
	dd 19.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal140_params:
	dd 18.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal141_params:
	dd 10.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal142_params:
	dd 5.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal143_params:
	dd 2.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal144_params:
	dd 9.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal145_params:
	dd 18.0
	dd 65.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal146_params:
	dd 18.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal147_params:
	dd 12.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal148_params:
	dd 1.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal149_params:
	dd 16.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal150_params:
	dd 2.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal151_params:
	dd 2.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal152_params:
	dd 2.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal153_params:
	dd 13.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal154_params:
	dd 11.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal155_params:
	dd 6.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal156_params:
	dd 6.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal157_params:
	dd 8.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal158_params:
	dd 9.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal159_params:
	dd 19.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal160_params:
	dd 0.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal161_params:
	dd 3.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal162_params:
	dd 19.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal163_params:
	dd 15.0
	dd 60.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal164_params:
	dd 10.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal165_params:
	dd 5.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal166_params:
	dd 16.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal167_params:
	dd 8.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal168_params:
	dd 18.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal169_params:
	dd 2.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal170_params:
	dd 9.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal171_params:
	dd 19.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal172_params:
	dd 11.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal173_params:
	dd 4.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal174_params:
	dd 3.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal175_params:
	dd 3.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal176_params:
	dd 15.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal177_params:
	dd 18.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal178_params:
	dd 11.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal179_params:
	dd 5.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal180_params:
	dd 15.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal181_params:
	dd 18.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal182_params:
	dd 4.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal183_params:
	dd 8.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal184_params:
	dd 14.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal185_params:
	dd 19.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal186_params:
	dd 4.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal187_params:
	dd 1.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal188_params:
	dd 1.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal189_params:
	dd 8.0
	dd 4.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal190_params:
	dd 13.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal191_params:
	dd 13.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal192_params:
	dd 18.0
	dd 1.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal193_params:
	dd 17.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal194_params:
	dd 1.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal195_params:
	dd 9.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal196_params:
	dd 13.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal197_params:
	dd 5.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal198_params:
	dd 6.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal199_params:
	dd 13.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal0_params:
	dd 4.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal1_params:
	dd 16.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal2_params:
	dd 1.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal3_params:
	dd 4.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal4_params:
	dd 15.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal5_params:
	dd 16.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal6_params:
	dd 4.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal7_params:
	dd 16.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal8_params:
	dd 9.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal9_params:
	dd 2.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal10_params:
	dd 0.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal11_params:
	dd 8.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal12_params:
	dd 2.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal13_params:
	dd 3.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal14_params:
	dd 8.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal15_params:
	dd 6.0
	dd 5.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal16_params:
	dd 6.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal17_params:
	dd 7.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal18_params:
	dd 14.0
	dd 5.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal19_params:
	dd 2.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal20_params:
	dd 9.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal21_params:
	dd 16.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal22_params:
	dd 0.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal23_params:
	dd 17.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal24_params:
	dd 14.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal25_params:
	dd 4.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal26_params:
	dd 12.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal27_params:
	dd 0.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal28_params:
	dd 4.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal29_params:
	dd 8.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal30_params:
	dd 8.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal31_params:
	dd 6.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal32_params:
	dd 15.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal33_params:
	dd 10.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal34_params:
	dd 17.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal35_params:
	dd 18.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal36_params:
	dd 17.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal37_params:
	dd 4.0
	dd 64.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal38_params:
	dd 13.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal39_params:
	dd 11.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal40_params:
	dd 6.0
	dd 60.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal41_params:
	dd 5.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal42_params:
	dd 13.0
	dd 6.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal43_params:
	dd 19.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal44_params:
	dd 8.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal45_params:
	dd 3.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal46_params:
	dd 2.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal47_params:
	dd 12.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal48_params:
	dd 18.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal49_params:
	dd 1.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal50_params:
	dd 14.0
	dd 6.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal51_params:
	dd 0.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal52_params:
	dd 2.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal53_params:
	dd 5.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal54_params:
	dd 13.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal55_params:
	dd 7.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal56_params:
	dd 15.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal57_params:
	dd 8.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal58_params:
	dd 13.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal59_params:
	dd 14.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal60_params:
	dd 4.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal61_params:
	dd 5.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal62_params:
	dd 14.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal63_params:
	dd 9.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal64_params:
	dd 10.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal65_params:
	dd 18.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal66_params:
	dd 12.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal67_params:
	dd 15.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal68_params:
	dd 4.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal69_params:
	dd 5.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal70_params:
	dd 5.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal71_params:
	dd 15.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal72_params:
	dd 6.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal73_params:
	dd 0.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal74_params:
	dd 8.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal75_params:
	dd 18.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal76_params:
	dd 12.0
	dd 61.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal77_params:
	dd 9.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal78_params:
	dd 18.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal79_params:
	dd 14.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal80_params:
	dd 19.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal81_params:
	dd 15.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal82_params:
	dd 15.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal83_params:
	dd 4.0
	dd 11.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal84_params:
	dd 13.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal85_params:
	dd 12.0
	dd 62.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal86_params:
	dd 7.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal87_params:
	dd 12.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal88_params:
	dd 6.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal89_params:
	dd 10.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal90_params:
	dd 13.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal91_params:
	dd 4.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal92_params:
	dd 16.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal93_params:
	dd 14.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal94_params:
	dd 18.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal95_params:
	dd 1.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal96_params:
	dd 17.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal97_params:
	dd 3.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal98_params:
	dd 17.0
	dd 5.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal99_params:
	dd 16.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal100_params:
	dd 5.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal101_params:
	dd 19.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal102_params:
	dd 14.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal103_params:
	dd 15.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal104_params:
	dd 13.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal105_params:
	dd 7.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal106_params:
	dd 0.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal107_params:
	dd 13.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal108_params:
	dd 6.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal109_params:
	dd 19.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal110_params:
	dd 18.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal111_params:
	dd 11.0
	dd 60.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal112_params:
	dd 9.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal113_params:
	dd 14.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal114_params:
	dd 19.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal115_params:
	dd 15.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal116_params:
	dd 3.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal117_params:
	dd 5.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal118_params:
	dd 14.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal119_params:
	dd 10.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal120_params:
	dd 15.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal121_params:
	dd 5.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal122_params:
	dd 7.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal123_params:
	dd 15.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal124_params:
	dd 6.0
	dd 2.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal125_params:
	dd 13.0
	dd 3.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal126_params:
	dd 7.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal127_params:
	dd 5.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal128_params:
	dd 8.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal129_params:
	dd 12.0
	dd 59.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal130_params:
	dd 2.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal131_params:
	dd 8.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal132_params:
	dd 6.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal133_params:
	dd 14.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal134_params:
	dd 14.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal135_params:
	dd 17.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal136_params:
	dd 11.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal137_params:
	dd 4.0
	dd 64.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal138_params:
	dd 18.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal139_params:
	dd 11.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal140_params:
	dd 3.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal141_params:
	dd 12.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal142_params:
	dd 11.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal143_params:
	dd 4.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal144_params:
	dd 1.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal145_params:
	dd 17.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal146_params:
	dd 15.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal147_params:
	dd 12.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal148_params:
	dd 2.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal149_params:
	dd 7.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal150_params:
	dd 6.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal151_params:
	dd 6.0
	dd 64.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal152_params:
	dd 17.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal153_params:
	dd 14.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal154_params:
	dd 16.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal155_params:
	dd 14.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal156_params:
	dd 16.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal157_params:
	dd 7.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal158_params:
	dd 7.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal159_params:
	dd 9.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal160_params:
	dd 7.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal161_params:
	dd 0.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal162_params:
	dd 1.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal163_params:
	dd 19.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal164_params:
	dd 6.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal165_params:
	dd 14.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal166_params:
	dd 0.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal167_params:
	dd 3.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal168_params:
	dd 15.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal169_params:
	dd 19.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal170_params:
	dd 16.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal171_params:
	dd 14.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal172_params:
	dd 16.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal173_params:
	dd 14.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal174_params:
	dd 11.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal175_params:
	dd 2.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal176_params:
	dd 10.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal177_params:
	dd 18.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal178_params:
	dd 3.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal179_params:
	dd 15.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal180_params:
	dd 5.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal181_params:
	dd 12.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal182_params:
	dd 7.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal183_params:
	dd 11.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal184_params:
	dd 1.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal185_params:
	dd 15.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal186_params:
	dd 6.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal187_params:
	dd 12.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal188_params:
	dd 8.0
	dd 1.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal189_params:
	dd 18.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal190_params:
	dd 19.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal191_params:
	dd 5.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal192_params:
	dd 19.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal193_params:
	dd 12.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal194_params:
	dd 12.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal195_params:
	dd 10.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal196_params:
	dd 10.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal197_params:
	dd 14.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal198_params:
	dd 0.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal199_params:
	dd 6.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal0_params:
	dd 1.0
	dd 0.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal1_params:
	dd 5.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal2_params:
	dd 16.0
	dd 5.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal3_params:
	dd 1.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal4_params:
	dd 11.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal5_params:
	dd 15.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal6_params:
	dd 1.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal7_params:
	dd 3.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal8_params:
	dd 18.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal9_params:
	dd 8.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal10_params:
	dd 10.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal11_params:
	dd 11.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal12_params:
	dd 19.0
	dd 2.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal13_params:
	dd 7.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal14_params:
	dd 14.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal15_params:
	dd 15.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal16_params:
	dd 3.0
	dd 61.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal17_params:
	dd 6.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal18_params:
	dd 5.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal19_params:
	dd 15.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal20_params:
	dd 1.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal21_params:
	dd 10.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal22_params:
	dd 7.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal23_params:
	dd 9.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal24_params:
	dd 12.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal25_params:
	dd 12.0
	dd 1.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal26_params:
	dd 1.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal27_params:
	dd 11.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal28_params:
	dd 6.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal29_params:
	dd 7.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal30_params:
	dd 18.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal31_params:
	dd 1.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal32_params:
	dd 13.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal33_params:
	dd 0.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal34_params:
	dd 11.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal35_params:
	dd 17.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal36_params:
	dd 13.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal37_params:
	dd 6.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal38_params:
	dd 11.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal39_params:
	dd 16.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal40_params:
	dd 4.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal41_params:
	dd 17.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal42_params:
	dd 12.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal43_params:
	dd 13.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal44_params:
	dd 11.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal45_params:
	dd 9.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal46_params:
	dd 18.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal47_params:
	dd 3.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal48_params:
	dd 17.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal49_params:
	dd 8.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal50_params:
	dd 1.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal51_params:
	dd 13.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal52_params:
	dd 1.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal53_params:
	dd 11.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal54_params:
	dd 10.0
	dd 41.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal55_params:
	dd 8.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal56_params:
	dd 15.0
	dd 36.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal57_params:
	dd 8.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal58_params:
	dd 17.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal59_params:
	dd 12.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal60_params:
	dd 1.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal61_params:
	dd 14.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal62_params:
	dd 15.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal63_params:
	dd 10.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal64_params:
	dd 12.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal65_params:
	dd 13.0
	dd 8.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal66_params:
	dd 2.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal67_params:
	dd 9.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal68_params:
	dd 12.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal69_params:
	dd 10.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal70_params:
	dd 14.0
	dd 47.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal71_params:
	dd 4.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal72_params:
	dd 17.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal73_params:
	dd 14.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal74_params:
	dd 12.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal75_params:
	dd 2.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal76_params:
	dd 11.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal77_params:
	dd 2.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal78_params:
	dd 0.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal79_params:
	dd 16.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal80_params:
	dd 8.0
	dd 6.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal81_params:
	dd 5.0
	dd 40.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal82_params:
	dd 1.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal83_params:
	dd 5.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal84_params:
	dd 14.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal85_params:
	dd 17.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal86_params:
	dd 11.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal87_params:
	dd 0.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal88_params:
	dd 5.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal89_params:
	dd 16.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal90_params:
	dd 19.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal91_params:
	dd 0.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal92_params:
	dd 0.0
	dd 42.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal93_params:
	dd 13.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal94_params:
	dd 13.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal95_params:
	dd 10.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal96_params:
	dd 10.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal97_params:
	dd 9.0
	dd 3.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal98_params:
	dd 6.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal99_params:
	dd 7.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal100_params:
	dd 14.0
	dd 60.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal101_params:
	dd 2.0
	dd 7.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal102_params:
	dd 7.0
	dd 31.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal103_params:
	dd 14.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal104_params:
	dd 11.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal105_params:
	dd 9.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal106_params:
	dd 12.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal107_params:
	dd 4.0
	dd 60.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal108_params:
	dd 16.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal109_params:
	dd 5.0
	dd 17.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal110_params:
	dd 19.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal111_params:
	dd 13.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal112_params:
	dd 14.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal113_params:
	dd 11.0
	dd 32.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal114_params:
	dd 11.0
	dd 18.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal115_params:
	dd 12.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal116_params:
	dd 7.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal117_params:
	dd 16.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal118_params:
	dd 19.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal119_params:
	dd 7.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal120_params:
	dd 16.0
	dd 35.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal121_params:
	dd 16.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal122_params:
	dd 3.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal123_params:
	dd 2.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal124_params:
	dd 2.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal125_params:
	dd 18.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal126_params:
	dd 12.0
	dd 21.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal127_params:
	dd 0.0
	dd 37.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal128_params:
	dd 14.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal129_params:
	dd 7.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal130_params:
	dd 13.0
	dd 61.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal131_params:
	dd 9.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal132_params:
	dd 5.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal133_params:
	dd 6.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal134_params:
	dd 0.0
	dd 44.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal135_params:
	dd 4.0
	dd 51.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal136_params:
	dd 2.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal137_params:
	dd 1.0
	dd 66.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal138_params:
	dd 10.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal139_params:
	dd 17.0
	dd 12.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal140_params:
	dd 9.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal141_params:
	dd 4.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal142_params:
	dd 6.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal143_params:
	dd 5.0
	dd 52.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal144_params:
	dd 12.0
	dd 48.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal145_params:
	dd 11.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal146_params:
	dd 10.0
	dd 30.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal147_params:
	dd 9.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal148_params:
	dd 14.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal149_params:
	dd 8.0
	dd 38.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal150_params:
	dd 8.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal151_params:
	dd 9.0
	dd 16.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal152_params:
	dd 10.0
	dd 34.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal153_params:
	dd 14.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal154_params:
	dd 5.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal155_params:
	dd 0.0
	dd 22.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal156_params:
	dd 0.0
	dd 46.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal157_params:
	dd 0.0
	dd 29.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal158_params:
	dd 4.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal159_params:
	dd 0.0
	dd 45.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal160_params:
	dd 9.0
	dd 10.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal161_params:
	dd 16.0
	dd 19.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal162_params:
	dd 18.0
	dd 6.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal163_params:
	dd 18.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal164_params:
	dd 19.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal165_params:
	dd 9.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal166_params:
	dd 4.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal167_params:
	dd 15.0
	dd 5.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal168_params:
	dd 5.0
	dd 56.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal169_params:
	dd 14.0
	dd 25.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal170_params:
	dd 19.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal171_params:
	dd 18.0
	dd 53.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal172_params:
	dd 11.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal173_params:
	dd 12.0
	dd 55.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal174_params:
	dd 13.0
	dd 58.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal175_params:
	dd 12.0
	dd 33.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal176_params:
	dd 13.0
	dd 27.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal177_params:
	dd 12.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal178_params:
	dd 19.0
	dd 4.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal179_params:
	dd 5.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal180_params:
	dd 9.0
	dd 54.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal181_params:
	dd 16.0
	dd 15.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal182_params:
	dd 6.0
	dd 57.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal183_params:
	dd 11.0
	dd 28.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal184_params:
	dd 13.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal185_params:
	dd 10.0
	dd 2.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal186_params:
	dd 12.0
	dd 49.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal187_params:
	dd 12.0
	dd 50.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal188_params:
	dd 8.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal189_params:
	dd 9.0
	dd 39.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal190_params:
	dd 13.0
	dd 26.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal191_params:
	dd 1.0
	dd 23.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal192_params:
	dd 3.0
	dd 20.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal193_params:
	dd 19.0
	dd 9.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal194_params:
	dd 13.0
	dd 24.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal195_params:
	dd 11.0
	dd 14.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal196_params:
	dd 2.0
	dd 63.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal197_params:
	dd 5.0
	dd 61.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal198_params:
	dd 9.0
	dd 13.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

pal199_params:
	dd 17.0
	dd 43.0
	dd 1.0
	dd 0.0
	dd 0.0
	dd 0.0

